---
# Original: https://pre-commit.com/
# Recommended: https://prek.j178.dev/

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-json
        exclude: |
          (?x)^(
            backup/[\d|\w|_]+\/(.*?)|
            docs/nodejs/ts_tutorial/tsconfig.json|
            path/to/file3.json
          )$
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-toml
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e  # frozen: v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: a4727cbbcd26d7098e96b9cb738169b59711ae51  # frozen: v1.24.1
    hooks:
      - id: zizmor

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 6d3c1b70d44ea2202b23552af93aca3b5017ee83  # frozen: v0.9.36
    hooks:
      - id: pymarkdown
        args:
          - --config=.config/.pymarkdown.yaml
          - scan
        exclude: |
          (?x)^(
            backup/[\d|\w|_]+\/(.*?)|
            habits/.*\.md|
            path/to/file3.py
          )$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args:
          - -c=.config/.yamllint

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 91ab4bf57e58b32adf1a122681f6ebe164d081c8  # frozen: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, build, chore, ci, docs, perf, refactor, revert, style, test, bump]
