# prefix
set-option -g prefix C-z
bind-key C-z send-prefix
unbind-key C-b

# terminal
set-option -g default-terminal xterm-256color
#set-option -g default-terminal screen-256color
set-option -g history-limit 10000
#set-option -g status-interval 5

# status color
set -g message-style "bg=red,fg=white"
set -g status-style "bg=cyan,fg=black"
set -g window-status-style "bg=cyan,fg=black"
set -g window-status-current-style "bg=black,fg=blue"

set -g status-right "%Y/%m/%d %a %H:%M "

# key

# | でペインを立てに分割する
bind | split-window -h

# - でペインを横に分割する
bind - split-window -v

set-window-option -g mode-keys vi
bind r source-file ~/.tmux.conf \; display "Reload configuration."
bind s set-window-option synchronize-panes
bind S run "tmux capture-pane -S -10000; tmux save-buffer ~/logs/tmux/tmux_capture-$(date '+%Y%m%d_%H%M%S')" \; display "Save history."
bind P pipe-pane -o "cat >> ~/logs/tmux/tmux-$(date '+%Y%m%d_%H%M%S').log" \; display "Toggled logging"
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r n next-window
bind -r p previous-window
bind V select-layout main-vertical \; swap-pane -s : -t 0 \; select-pane -t 0 \; resize-pane -R 40
bind H select-layout main-horizontal \; swap-pane -s : -t 0 \; select-pane -t 0 \; resize-pane -D 15

# Other options
# see https://superuser.com/questions/295736/tmux-status-bar-messages-last-only-about-a-second-can-i-extend-this
set-option -g display-time 2000

