# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev/

version: "3"

vars:
  # 一連の処理のエラーを捕捉（_gitで使用する）
  # 以前は defer で task に vars が渡せていたが、v3.39.0 あたりでエラーになって以降
  # 修正されておらず、グローバルに切り出して対応することにした
  ON_ERROR: /tmp/on_error_aqua

tasks:
  default:
    cmds:
      - task --list --sort alphanumeric -t {{.TASKFILE}}
      - echo ""
      - echo -n "reminder this package "
      - task: packages
    silent: true

  alias:
    desc: show alias for aqua
    summary: |
      aqua のエイリアスを表示
      profile を引き継がないので alias コマンドから grep では表示できないのでベタ書き
    aliases:
      - aa
    cmds:
      - |
        cat <<EOF
        alias aqgi='aqua generate -i -o $AQUA_GLOBAL_CONFIG'
        alias aqia='aqua install --all'
        alias aqli='aqua list --installed --all | sort'
        alias aqup='aqua update'
        EOF
    silent: true

  packages:
    desc: random package from aqua.yaml
    aliases:
      - ap
    vars:
      AQUA_YAML_FILE:
        sh: cat aqua.yaml
        # yq を強要せずに aqua.yaml の内容を取得する
      AQUA_YAML_DATA:
        ref: fromYaml .AQUA_YAML_FILE
        # YAML をパースしてデータを取得
      AQUA_YAML_DATA_LENGTH:
        ref: len .AQUA_YAML_DATA.packages
        # パッケージの数を取得
      RANDOM_PACKAGE:
        ref: index .AQUA_YAML_DATA.packages (randInt 0 .AQUA_YAML_DATA_LENGTH)
        # ランダムなパッケージを取得
    cmds:
      - echo "{{.RANDOM_PACKAGE.name}}"
    silent: true

  update:
    desc: Run aqua update, install, list for globally
    aliases:
      - au
    dir: ~/.config/aqua
    dotenv:
      - .env
    cmds:
      - echo "use github token [${GITHUB_TOKEN:0:20}***]"
      - aqua update
      - aqua install -all
      - aqua list --installed --all | sort

  git:
    desc: auto git, use -- COMMIT TITLE
    summary: |
      aqua update の結果を自動で登録
      task ag -- コミットタイトル（の一部）
    aliases:
      - ag
    cmds:
      - task: _git
        vars:
          TITLE: 'bump: aqua up at {{date "2006-01-02" now}} {{.CLI_ARGS}}'
          BRANCH: 'bump/aqua_up/{{date "2006-01-02" now}}'
          TARGET: "aqua.yaml"

  _git:
    summary: git automation
    requires:
      vars:
        - TITLE
        - BRANCH
        - TARGET
    cmds:
      - defer:
          task: _git:on_error
      - touch {{.ON_ERROR}}
      - task: _git:auto
        vars:
          TITLE: "{{.TITLE}}"
          BRANCH: "{{.BRANCH}}"
          TARGET: "{{.TARGET}}"
      - task: _git:gh
        vars:
          TITLE: "{{.TITLE}}"
          BRANCH: "{{.BRANCH}}"
      - git fetch --prune --all
      - task: _git:status
      - rm {{.ON_ERROR}}

  _git:auto:
    summary: |
      git add, commit, push までを自動化
    cmds:
      - git fetch --prune --all
      - git checkout origin/HEAD
      - git add {{.TARGET}}
      - git commit -m"{{.TITLE}}"
      - git push origin HEAD:refs/heads/{{.BRANCH}} -f

  _git:gh:
    summary: |
      - GitHub CLI を使用して PR を作成し、オートマージを設定する
      - push 前までと分離しているのは、エラー時の処理が異なるため
        - push 前までのエラーは reset して処理前に戻す
        - push 後のエラーは push を再処理する（ON_ERROR のファイルに保存）
      - PAT の権限がちゃんとしてないとエラーになることに注意
      - オートマージの設定もリポジトリ側に必要
    cmds:
      - gh pr create -t "{{.TITLE}}" -b "" -l "" -H "{{.BRANCH}}" -B "main"
      - sleep 1
      - gh pr merge "{{.BRANCH}}" --auto -s
      - sleep 2

  _git:status:
    internal: true
    cmds:
      # see https://github.com/officel/config_git/blob/main/config#L21
      - git plog -5
      - git status --short --branch

  _git:on_error:
    internal: true
    silent: true
    status:
      # エラーファイルが存在したら処理する
      - test ! -e {{.ON_ERROR}}
    cmds:
      - defer: rm {{.ON_ERROR}}
      - cmd: git reset --mixed origin/HEAD
        ignore_error: true
      - task: _git:status
