# .dotfiles/alias

# ansible
# alias ansible-playbook='TZ="Asia/Tokyo" ANSIBLE_LOG_PATH=logs/ansible_$(date "+%Y%m%d%H%M%S").log ansible-playbook'
# alias ansible-groups='ansible-inventory --list | jq -r "keys | .[]"'

# k8s use kubecolor
alias k='kubecolor'
alias kubectl='kubecolor'
alias ka='kubectl apply'
alias kd='kubectl describe'
alias krm='kubectl delete'
alias kg='kubectl get'
alias kga='kubectl get all'
alias kgn='kubectl get node -o wide'
alias kgp='kubectl get pod'
alias kgx='kubectl get all,pv,pvc,job,ing'
alias kgpa='kubectl get pod -A'
alias kgtn='kubectl get node -o wide; kubectl top node'
alias kdrainf='kubectl drain --ignore-daemonsets --delete-local-data'
alias stern='kubectl stern'
alias aliask='alias | grep kubectl'

# k9s
alias k9s='LC_CTYPE="en_US.UTF-8" k9s'
alias k9sr='LC_CTYPE="en_US.UTF-8" k9s --readonly'
